# This code scans the ICE-Nigeria corpus and counts occurrences
# of selected nation-related keywords in each text file, allowing us to rank
# and filter documents based on their relevance to the research topic.

import os
import re
from collections import Counter
from collections import defaultdict

# path to Data folder (choose between spoken/written)
folder_path1 = "../Data/ice-nig/txt - without speaker tags/spoken"
folder_path2 = "../Data/ice-nig/txt - without speaker tags/written"

# keywords (expandable)
keywords =  [
    "nation",
    "state",
    "country",
    "republic",
    "democracy",
    "monarchy",
    "federation",
    "confederation",
    "sovereignty",
    "territory",
    "regime",
    "government",
    "constitution",
    "parliament",
    "senate",
    "legislature",
    "citizenship",
    "polity",
    "commonwealth",
    "province",
    "prefecture",
    "municipality",
    "canton",
    "dominion",
    "protectorate",
    "colony",
    "empire",
    "realm",
    "kingdom",
    "principality",
    "mandate",
    "autonomy",
    "statehood",
    "nationhood",
    "self-determination",
    "governance",
    "administration",
    "authority",
    "jurisdiction",
    "identity",
    "belonging",
    "heritage",
    "roots",
    "ancestry",
    "lineage",
    "origin",
    "descent",
    "kinship",
    "ethnicity",
    "race",
    "culture",
    "tradition",
    "custom",
    "folklore",
    "myth",
    "memory",
    "nostalgia",
    "homeland",
    "motherland",
    "fatherland",
    "birthplace",
    "native",
    "indigenous",
    "autochthonous",
    "diaspora",
    "exile",
    "emigrant",
    "immigrant",
    "refugee",
    "expatriate",
    "foreigner",
    "alien",
    "naturalization",
    "assimilation",
    "integration",
    "multiculturalism",
    "cosmopolitanism",
    "tribalism",
    "sectarianism",
    "flag",
    "anthem",
    "coat of arms",
    "seal",
    "passport",
    "border",
    "boundary",
    "frontier",
    "territory",
    "map",
    "currency",
    "language",
    "dialect",
    "accent",
    "script",
    "literature",
    "cuisine",
    "dress",
    "costume",
    "monument",
    "landmark",
    "capital",
    "metropolis",
    "soil",
    "land",
    "landscape",
    "geography",
    "region",
    "homeland",
    "sacred site",
    "memorial",
    "museum",
    "archive",
    "institution",
    "people",
    "nation-state",
    "populace",
    "citizenry",
    "community",
    "society",
    "collective",
    "solidarity",
    "unity",
    "cohesion",
    "allegiance",
    "loyalty",
    "patriotism",
    "nationalism",
    "chauvinism",
    "jingoism",
    "nativism",
    "populism",
    "separatism",
    "irredentism",
    "unionism",
    "federalism",
    "devolution",
    "secession",
    "partition",
    "unification",
    "diaspora",
    "minority",
    "majority",
    "plurality",
    "demographics",
    "census",
    "ethnogenesis",
    "rights",
    "duties",
    "obligations",
    "allegiance",
    "naturalization",
    "citizenship",
    "nationality",
    "statelessness",
    "asylum",
    "sovereignty",
    "self-governance",
    "autonomy",
    "constitution",
    "charter",
    "treaty",
    "referendum",
    "election",
    "suffrage",
    "representation",
    "civic",
    "civil",
    "public",
    "common",
    "national",
    "federal",
    "international",
    "supranational",
    "transnational",
    "pride",
    "honor",
    "glory",
    "dignity",
    "freedom",
    "liberty",
    "independence",
    "sovereignty",
    "resistance",
    "struggle",
    "sacrifice",
    "martyrdom",
    "heroism",
    "myth",
    "narrative",
    "ideology",
    "conservatism",
    "progressivism",
    "liberalism",
    "republicanism",
    "authoritarianism",
    "totalitarianism",
    "imperialism",
    "colonialism",
    "postcolonialism",
    "decolonization",
    "emancipation",
    "revolution",
    "reform",
    "tradition",
    "modernity",
    "secularism",
    "theocracy",
    "history",
    "memory",
    "commemoration",
    "monument",
    "archive",
    "museum",
    "historiography",
    "myth",
    "legend",
    "epic",
    "oral tradition",
    "ritual",
    "ceremony",
    "festival",
    "holiday",
    "pilgrimage",
    "sacred",
    "secular",
    "generational",
    "legacy",
    "continuity",
    "rupture",
    "colonization",
    "decolonization",
    "occupation",
    "liberation",
    "resistance",
    "revolution",
    "founding",
    "constitution",
    "independence day",
    "land",
    "soil",
    "territory",
    "frontier",
    "border",
    "boundary",
    "region",
    "place",
    "homeland",
    "landscape",
    "countryside",
    "urban",
    "rural",
    "center",
    "periphery",
    "north",
    "south",
    "east",
    "west",
    "heartland",
    "hinterland",
    "coast",
    "interior",
    "enclave",
    "exclave",
    "zone",
    "corridor",
    "buffer",
    "basin",
    "capital",
    "us",
    "them",
    "other",
    "foreigner",
    "stranger",
    "insider",
    "outsider",
    "native",
    "settler",
    "colonizer",
    "colonized",
    "citizen",
    "non-citizen",
    "migrant",
    "nomad",
    "refugee",
    "stateless",
    "displaced",
    "rooted",
    "uprooted",
    "hybrid",
    "mixed",
    "blended",
    "creole",
    "syncretic"
]

def function_word_counts(file) :
    # store results
    file_counts = {}
    total_counts = Counter()

    for root, dirs, files in os.walk(file):
        for filename in files:
            if filename.endswith(".txt"):
                file_path = os.path.join(root, filename)

                with open(file_path, "r", encoding="utf-8") as f:
                    text = f.read().lower()

                    counts = {kw: len(re.findall(rf"\b{kw}s?\b", text)) for kw in keywords}

                    total = sum(counts.values())
                    file_counts[file_path] = {"total": total, **counts}

                    total_counts.update(counts)

    # sort files by relevance
    sorted_files = sorted(file_counts.items(), key=lambda x: x[1]["total"], reverse=True)

    print("\nTotal counts across corpus:\n", total_counts)

    word_counter = defaultdict(lambda: {"total": 0, "files": {}})

    for fname, counts in file_counts.items():
        for word, count in counts.items():
            if word == "total" or count == 0:
                continue
            word_counter[word]["total"] += count
            word_counter[word]["files"][fname] = count

    # sort words by total occurrences
    sorted_words = sorted(word_counter.items(), key=lambda x: x[1]["total"], reverse=True)

    # print breakdown
    for word, data in sorted_words[:40]:
        print(f"\n'{word}' — {data['total']} occurrences across {len(data['files'])} files")
        for fname, count in sorted(data["files"].items(), key=lambda x: x[1], reverse=True)[:5]:
            print(f"  {count:>4}x  {fname}")
    return None

function_word_counts(folder_path1)
function_word_counts(folder_path2)
